version: "3.5"
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dital
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

networks:
  dital:
    external: true
