version: "3.5"
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ditalnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

networks:
  ditalnet:
    external: true
