version: "3.5"

services:
  laravel-app:
    image: qloud77/dital-laravel
    ports:
      - "80:80"
    networks:
      - dital

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dital
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dital
      MYSQL_DATABASE: dital
      MYSQL_PASSWORD: dital

networks:
  dital:
    external: true
