version: "3.5"

services:
  app:
    image: qloud77/dss
    container_name: app
    ports:
      - "3000:80"

  lumen:
    image: qloud77/lumen
    container_name: lumen
    ports:
      - "8090:80"
    networks:
      - ditalnet

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - ditalnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    volumes:
      - data:/var/lib/mysql/test

networks:
  ditalnet:
    external: true

volumes:
  data:
    driver: "local"
