version: "3.5"

services:
  kalmar:
    image: qloud77/dital
    ports:
      - "8090:80"
    networks:
      - dital
    environment:
      - database=db
      - OFFICE=Kalmar

  karlskrona:
    image: qloud77/dital
    ports:
      - "8091:80"
    networks:
      - dital
    environment:
      - database=db
      - OFFICE=Karlskrona

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - dital
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

networks:
  dital:
    external: true
