version: "3.5"

services:
  app:
    image: qloud77/dital-laravel
    ports:
      - "8080:80"
    networks:
      - dital

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /dital:/var/lib/mysql
    restart: always
    ports:
      - "33060:3306"
    networks:
      - dital
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dital
      MYSQL_DATABASE: dital
      MYSQL_PASSWORD: dital

networks:
  dital:
    external: true
