version: "3.5"

services:
  app:
    image: qloud77/dital-app
    container_name: app
    ports:
      - "3000:80"

  api:
    image: qloud77/api
    container_name: api
    command: npm run prod
    ports:
      - "8090:3000"
    networks:
      - ditalnet

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ditalnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

networks:
  ditalnet:
    external: true
