version: "3.5"

services:
  kalmar:
    image: qloud77/dital
    ports:
      - "8090:80"
    networks:
      - dital
    environment:
      - database=db
      - OFFICE=Kalmar

  karlskrona:
    image: qloud77/dital
    ports:
      - "8091:80"
    networks:
      - dital
    environment:
      - database=db
      - OFFICE=Karlskrona

networks:
  dital:
    external: true
